#!/bin/bash

for i in $(ipcs -s | grep 0x | awk '{print $2}'); do ipcrm -s $i; done
for i in $(ipcs -m | grep 0x | awk '{print $2}'); do ipcrm -m $i; done
for i in $(ipcs -q | grep 0x | awk '{print $2}'); do ipcrm -q $i; done